### ISSUE TITLE
Invalid Character when syncing with ownCloud

### ISSUE THREAD

**Issue by ghost** [gs93/pakbak#2]
Hey, I just wanted to syn the backup with ownCloud but I get the error message `File contains invalid characters that can not be synced cross plattform`. It could be the `+` or the `:` I am not sure. Can you update it that it can be synced with ownCloud. Thanks!

**Comment by gs93** [comment]
I just removed both characters. The plus sign/timezone isn't necessary and the colon is forbidden on NTFS (I think that could create problems with a lot of sync services).

**Comment by ghost** [comment]
Amazing. Just updated and it works flawless. Great job! :thumbsup:
