### ISSUE TITLE
`$target_folder` as symbolic link

### ISSUE THREAD

**Issue by vltr** [gs93/pakbak#3]
Hello! I don't know if this is a misuse of mine, but I set `$target_folder` to a soft symbolic link. The problem is that `find` returns nothing, exiting the (`pakbak`) script on `stat` if `$keep_days` is set. I made a quick fix (for my case only), adding a slash at the end of `$target_folder`:

``` bash
find "$target_folder/" -name 'pakbak-*.tar.xz' -type f -print0 | xargs -0 stat --format "%Y %n" | sort -rn | cut -d' ' -f2- | tail -n +$keep_number | xargs -d'\n' rm;
```

If I set `$keep_days` too, I would need to "fix" the other `find` command.

Please, let me know your thoughts!

My best regards,
Richard.

**Comment by gs93** [comment]
Hello, sorry for the long delay. I added the `-H` parameter to find ("Do  not  follow  symbolic  links,  except  while processing the command line arguments.") instead of adding a slash because it's clearer.

**Comment by vltr** [comment]
No problem! Thanks for fixing it! The `-H` is clearer, indeed, as I just needed to make it work :smile:
