### ISSUE TITLE
find: missing argument to `-exec'

### ISSUE THREAD

**Issue by WarmChocolateCake** [gs93/pakbak#6]
I've just noticed that pakbak.service was failing.
When running it manually, I get:

```
sudo /usr/lib/systemd/scripts/pakbak
tar: Removing leading `/' from member names
find: missing argument to `-exec'

```

Looking at the code, there's a trailing + at line 47:
`find -H "$target_folder" -name 'pakbak-*.tar.xz' -type f -mtime +$keep_days -exec rm -v {} +
`

removing the trailing "+" seems to fix this problem, but I'm not sure whether that was supposed to be there for a reason? :)

**Comment by gs93** [comment]
I'm not sure why you're encountering this error and why removing the plus is fixing it. The trailing plus symbol is for find to know when the command for -exec is finished.

>      -exec command {} +
>              This  variant  of  the -exec action runs the specified command on the selected files, but the command line is built by appending each selected file name at the end; the total number of invocations of the command will be
>              much less than the number of matched files.  The command line is built in much the same way that xargs builds its command lines.  Only one instance of `{}' is allowed within the command.  The command is executed in  the
>              starting directory.  If find encounters an error, this can sometimes cause an immediate exit, so some pending commands may not be run at all.  This variant of -exec always returns true.

If this error is still occuring, could you provide your config file?

**Comment by WarmChocolateCake** [comment]
Thanks for getting back to me - I'd forgotten I'd raised this.

Looking at 1 system, I've re-installed it and it's working fine.

I'll check my other system later and see if that's working too - but whatever the problem was, this looks like it's working OK now.
Perhaps I had more files in the pacman cache than the command line could handle? I've currently got 7621 files in there and it works fine... I added 10k more files (0 bytes) and it still worked fine.

I think we can close this.

Thanks for creating this btw :)
